export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const TOGGLE_RECIPE = 'TOGGLE_RECIPE';
export const TOGGLE_CHECKBOX_RECIPE = 'TOGGLE_CHECKBOX_RECIPE';
export const RESET_RECIPE = 'RESET_RECIPE';
export const EXPORT_RECIPE = 'EXPORT_RECIPE';
