export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const TOGGLE_RECIPE = 'TOGGLE_RECIPE';
export const TOGGLE_RECIPE_STATE = 'TOGGLE_RECIPE_STATE';
export const DISCARD_RECIPE = 'DISCARD_RECIPE';
export const EXPORT_RECIPE = 'EXPORT_RECIPE';
